title: GesturePointer
description: Gesturing tool <description>
theme: just-the-docs

url: https://NMKsas.github.io/gesture_pointer_docs

aux_links:
  Source Code Repository: https://github.com/NMKsas/gesture_pointer
